codecov:
  max_report_age: off  # حتى ما يصير Expired لو تأخرت رَنّة

coverage:
  status:
    project:
      total:          # ستاتس للإجمالي (frontend+backend)
        target: auto
        threshold: 1%
      frontend:       # ستاتس منفصل للفرونت (flag-based)
        flags: [frontend]
        target: auto
        threshold: 1%
      backend:        # ستاتس منفصل للباك (flag-based)
        flags: [backend]
        target: auto
        threshold: 1%

# (اختياري) Components حسب المسارات لو بتحب لوحة "Components"
component_management:
  individual_components:
    - component_id: frontend
      name: Frontend
      paths:
        - "src/**"
    - component_id: backend
      name: Backend
      paths:
        - "backend/**"
