codecov:
  require_ci_to_pass: false

flags:
  frontend:
    paths:
      - src/
  backend:
    paths:
      - backend/

coverage:
  precision: 2
  status:
    project:
      default: off
      frontend:
        flags: frontend
        target: auto
        threshold: 1%
      backend:
        flags: backend
        target: auto
        threshold: 1%
    patch:
      default: off
      frontend:
        flags: frontend
        target: auto
        threshold: 1%
      backend:
        flags: backend
        target: auto
        threshold: 1%
